apiVersion: v1
kind: Pod
metadata: 
  labels: 
    name: voting-app-pod
    app: demo-voting-app
  name: voting-app-pod
spec: 
  containers: 
    - 
      image: docker/example-voting-app-vote:latest
      name: voting-app
      ports:
       - containerPort: 80
