apiVersion: v1
kind: Pod
metadata: 
  labels: 
    name: worker-app-pod
    app: demo-voting-app
  name: worker-app-pod
spec: 
  containers: 
    - 
      image: docker/example-voting-app-worker
      name: worker-app